<?php

namespace Sonar;

require_once( "Config.php" );
require_once( "Error.php" );
require_once( "User.php" );

class Commenting extends __Error
{
    private $_db,
            $_commentsTableName,
            $_maxLevel,
            $_comments,
            $_postID;
    
    public function __construct( $tableName, $postID )
    {
        if ( Config::get( "mysql/enabled" ) )
        {
            $this->_db = DB::getInstance( );
            
            $this->_commentsTableName = $tableName;
        }
        
        $this->_postID = $postID;
        
        $this->_maxLevel = 1;
    }
    
    public function SetMaxNestingLevel( $maxLevel )
    {
        $this->_maxLevel = $maxLevel;
    }
    
    public function GetMaxNestingLevel( )
    {
        return $this->_maxLevel;
    }
    
    private function LoadComments( $column, $id )
    {
        $this->_db->get( $this->_commentsTableName, array( $column, "=", $id ) );
        
        // check if comments exist for the requested id
        if ( $this->_db->Count( ) )
        {
            $this->_comments = $this->_db->Results( );
            
    		return true;
    	}
        else
        {
            return false;
        }
    }
    
    private function GetComments( $column, $id, $forceLoad )
    {
        // force loads/retrieves the comments from the database
        if ( $forceLoad )
        {
            $this->LoadComments( $column, $id );
        }
        
        // check if comments exist for the requested id
        if ( $this->Count( ) )
    	{
    		return $this->_comments;
    	}
        else
        {
            return false;
        }
    }
    
    public function GetCommentsForPostID( $postID, $forceLoad = true )
    {
        return $this->GetComments( "postid", $postID, $forceLoad );
    }
    
    public function GetCommentsForUserID( $userID, $forceLoad = true )
    {
        return $this->GetComments( "userid", $userID, $forceLoad );
    }
    
    public function GetCommentsForParentID( $parentID, $forceLoad = true )
    {
        return $this->GetComments( "parentid", $parentID, $forceLoad );
    }
    
    public function GetCommentsForID( $id, $forceLoad = true )
    {
        return $this->GetComments( "id", $id, $forceLoad );
    }
    
    // get number of comments for post
    public function Count( )
    {
        return $this->_db->Count( );
    }
    
    public function InsertComment( $comment, $parentID = 0, $timeedited = 0 )
    {
        // postid TICK
        // parentid (optional otherwise 0)
        // userid
        // timeposted (autogenerated) TICK
        // timeedited (optional otherwise 0)
        // description TICK
        
        // CHECKS ( return false if failed anyone of these checks) [POTENTIALLY USE ERROR FUNCTIONALITY BUILT IN]
        // check if user is logged in TICK
        // check if parent id is not 0
            // check if parent id exists for the post
            // check if parent currentnestedlevel is lower that maxnestedlevel
        // 
        
        $user = new User( );
        
        if ( !$user->isLoggedIn( ) )
        {
            $this->addError( "Unable to post comment at this time, please try again later." );

            return false;
        }
        else if ( 0 !== $parentID )
        {
            
        }
        
        return $comment;
        
        $fields = array(
            "postid" => $this->_postID,
            "parentid" => $parentID,
            "userid" => $user->Data( )->id,
            "timeposted" => time( ),
            "timeedited" => $timeedited,
            "description" => $comment
        );

        if ( !$this->_db->insert( $this->_commentsTableName, $fields ) )
        {
            return false;
        }
        else
        {
            return true;
        }
    }
}